# syntax=docker/dockerfile:1

FROM node:lts-alpine AS builder

WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker's caching
COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:lts-alpine AS runner

WORKDIR /app

# Set Node environment to development
ENV NODE_ENV=development

# Copy only necessary files from the builder stage
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Expose the port Next.js runs on (default 3000)
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

#CMD ["npm", "run", "dev"]

# Start the Next.js server
CMD ["node", "server.js"]